import os
import json
import numpy as np
import soundfile as sf

audio_dir = "/root/Ambit/videos/ambit-demo/audio"
sr = 48000

# Load audio metadata generated by generate_audio_reference.py
with open("/root/Ambit/videos/ambit-demo/audio_meta.json", "r") as f:
    meta = json.load(f)

print(f"Loaded {len(meta)} shots from audio_meta.json.")

# Total speech duration
total_speech = meta[-1]["end"]
# Add a 3.0s buffer at the end for final brand fadeout
total_dur = round(total_speech + 3.0, 2)
total_len = int(sr * total_dur)
master = np.zeros(total_len, dtype=np.float32)

print(f"Total video duration: {total_dur}s ({total_len} samples at {sr}Hz)")

# Load Ambient BGM
bgm_path = os.path.join(audio_dir, "ambient_bgm_48k.wav")
bgm, bgm_sr = sf.read(bgm_path)
if bgm_sr != sr:
    raise ValueError(f"BGM sample rate {bgm_sr} != {sr}")

# If stereo, average to mono
if len(bgm.shape) > 1:
    bgm = np.mean(bgm, axis=1)

# Loop or trim BGM to fit total_len
if len(bgm) < total_len:
    repeats = int(np.ceil(total_len / len(bgm)))
    bgm = np.tile(bgm, repeats)[:total_len]
else:
    bgm = bgm[:total_len]

# Ducking envelope: 1.0 during silence, 0.22 during speech
duck = np.ones(total_len, dtype=np.float32)

for item in meta:
    vo_path = item["file"]
    if not os.path.exists(vo_path):
        print(f"Warning: {vo_path} not found")
        continue
    vo, vo_sr = sf.read(vo_path)
    if vo_sr != sr:
        raise ValueError(f"VO {vo_path} sample rate {vo_sr} != {sr}")
    if len(vo.shape) > 1:
        vo = np.mean(vo, axis=1)
        
    start_idx = int(item["start"] * sr)
    end_idx = start_idx + len(vo)
    if end_idx > total_len:
        vo = vo[:total_len - start_idx]
        end_idx = total_len
        
    master[start_idx:end_idx] += vo * 0.95
    
    # Duck BGM
    duck_start = max(0, start_idx - int(0.35 * sr))
    duck_end = min(total_len, end_idx + int(0.45 * sr))
    duck[duck_start:duck_end] = 0.22

# Apply ducking to BGM
master += (bgm * duck) * 0.45

# SFX directory
sfx_dir = "/root/.agents/skills/media-use/audio/assets/sfx"

def load_sfx(name):
    p = os.path.join(sfx_dir, name)
    if os.path.exists(p):
        data, s_sr = sf.read(p)
        if s_sr != sr:
            # simple resample or fallback
            pass
        if len(data.shape) > 1:
            data = np.mean(data, axis=1)
        return data
    return None

chime = load_sfx("ui_chime.wav")
click = load_sfx("mouse_click.wav")
error_sfx = load_sfx("error_refusal.wav")
ping = load_sfx("affirmative_ping.wav")

def add_sfx(sfx_data, at_time, gain=0.5):
    if sfx_data is None:
        return
    s_idx = int(at_time * sr)
    e_idx = s_idx + len(sfx_data)
    if e_idx <= total_len:
        master[s_idx:e_idx] += sfx_data * gain

# SFX cue timing based on shot start times
for item in meta:
    s_time = item["start"]
    name = item["name"]
    # transition click on each shot start
    add_sfx(click, s_time + 0.1, gain=0.35)
    
    if name == "shot1_job":
        add_sfx(chime, s_time + 0.5, gain=0.4)
    elif name == "shot4_decisions":
        # ALLOW affirmative ping
        add_sfx(ping, s_time + 6.0, gain=0.45)
        # Refusal error tone on DUPLICATE_INTENT
        add_sfx(error_sfx, s_time + 14.0, gain=0.5)
    elif name == "shot5_settlement":
        # On-chain settlement chime
        add_sfx(chime, s_time + 12.0, gain=0.45)
    elif name == "shot7_outro":
        # Final closing chime
        add_sfx(chime, s_time + 0.8, gain=0.5)

# Smooth master fade out at tail (last 3.0s)
fade_out_samples = int(3.0 * sr)
master[-fade_out_samples:] *= np.linspace(1, 0, fade_out_samples)

# Normalize to -1 dB peak (0.89)
peak = np.max(np.abs(master))
if peak > 0:
    master = master * (0.89 / peak)

out_file = os.path.join(audio_dir, "master_audio.wav")
sf.write(out_file, master, sr)
print(f"Master audio mixed successfully: {out_file} ({total_dur}s at {sr}Hz)")
